module.exports = [
    {
        title: "The 7 Habits of Highly Effective People",
        description: "The Seven Habits of Highly Effective People (1989) is the enormously influential self-help phenomenon that can teach you the principles of effectiveness. Once you make these principles into habits, you’ll be well on your way to more success, both in your personal and your professional life.",
        genre: "Self Help",
        url:"https://res.cloudinary.com/ddkl6dxmh/image/upload/v1618765105/YelpCamp/znbjjkqpjdpsqmuwrftt.jpg",
        filename:"YelpCamp/znbjjkqpjdpsqmuwrftt",
    },
    {
        title: "How to Win Friends & Influence People",
        description: "How to Win Friends & Influence People (first published in 1936, this edition from 1981) is considered the quintessential self-help book. Many prominent people from Warren Buffett to Lee Iacocca point to its techniques as one of the secrets of their success. Examples and anecdotes will make Carnegie’s advice concrete enough for you to easily implement it in your own life.",
        genre: "Self Help",
        url:"https://res.cloudinary.com/ddkl6dxmh/image/upload/v1618088863/YelpCamp/ehwmomiamw4rszxjq3m1.jpg",
        filename:"YelpCamp/ehwmomiamw4rszxjq3m1",
    },
    {
        title: "The Power of Now",
        description: "The Power of Now (1997) offers a specific method for putting an end to suffering and achieving inner peace, living fully in the present and separating yourself from your mind. The book also teaches you to detach yourself from your “ego” – a part of the mind that seeks control over your thinking and behavior. It argues that by doing so you can learn to accept the present, reduce the amount of pain you experience, improve your relationships and enjoy a better life in general.",
        genre: "Motivation",
    },
    {
        title: "Think and Grow Rich",
        description: "In Think and Grow Rich (1937), Napoleon Hill investigates the methods of the 500 most successful people of his time, including the world’s richest men, top politicians, famous inventors, writers and captains of industry. First published amidst the Great Depression, Think and Grow Rich has sold over 100 million copies.",
        genre: "Entrepreneurship",
    },
    {
        title: "How to Stop Worrying and Start Living",
        description: "How to Stop Worrying and Start Living (1948) is a self-help classic that outlines clearly why worrying is bad for you and what you can do about it. With tools and techniques to put to action, as well as a wealth of examples and anecdotes to back up its recommendations, How to Stop Worrying and Start Living can help you worry less today.",
        genre: "Self Help",
    },
    {
        title: "Never Eat Alone",
        description: "In Never Eat Alone, Keith Ferrazzi, a successful businessman and marketing expert, takes us through the secrets to successful networking. He focuses on building lasting relationships rather than merely exchanging business cards, which seems to be many people’s idea of networking today. He summarizes his findings in a system of tried and tested methods.",
        genre: "Fiction",
    },
    {
        title: "You Are a Badass",
        description: "You Are a Badass (2013) is your guide to living life to the fullest. Sincero provides an analysis of exactly what’s holding you back and provides powerful strategies geared toward breaking bad habits so that you can truly live out your dreams.",
        genre: "Self Help",
    },
    {
        title: "Blink",
        description: "Blink examines the phenomenon of snap judgments, meaning the split-second decisions we make unconsciously. These snap judgments are important decision-making tools, but can also lead to bad choices and all manner of problems. Blink explains how we can best make use of them.",
        genre: "Motivation",
    },
    {
        title: "Atomic Habits",
        description: "Atomic Habits (2018) provides a practical and proven framework for creating good habits and shedding bad ones. Drawing on scientific research and real-life examples, it shows how tiny changes in behavior can result in the formation of new habits and help you achieve big things.",
        genre: "Self Help",
    },
    {
        title: "The 80/20 Principle",
        description: "The 80/20 Principle (1997) was named one of GQ's Top 25 Business Books of the Twentieth Century. It's about the 80/20 principle, which says that 80 percent of results are generated by just 20 percent of effort. This phenomenon has huge implications for every area of life, as it helps single out the most important factors in any situation.",
        genre: "Entrepreneurship",
        url:"https://res.cloudinary.com/ddkl6dxmh/image/upload/v1618765105/YelpCamp/znbjjkqpjdpsqmuwrftt.jpg",
        filename:"YelpCamp/znbjjkqpjdpsqmuwrftt",
    },
];
